sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  redis:
    host: 192.168.10.70
    port: 6379
    password: 111111
    database: 0

  alioss:
    access-key: lRMJbOk3eRmH0vUwAMR_X0aLgggJ6KaQ-F1WEsY3
    access-secret: 1PGl1Km_HwxCM94E7NHcUs6Ce32MuNCDiKX4JRR5
    bucket-name: likkjxx-sky-take-out
    endpoint: http://sa2kra4y7.hd-bkt.clouddn.com
